title: HNPaper/news
description: Actualités automatisées depuis hnpaper (https://hnpaper-labs.gaidot.net)
theme: jekyll-theme-hacker
url: https://rgaidot.github.io
baseurl: ""

permalink: /posts/:year/:month/:day/:title/

lang: fr
timezone: Europe/Paris

paginate: 10
paginate_path: "/page:num/"
plugins:
  - jekyll-paginate
